// Components/places.js

export const CATEGORIES = [
    {
      id: 'historical',
      title: 'Historical places',
      cover: require('../assets/historical-cover.png'),
      items: [
        {
          id: 'fort-barriere',
          name: 'Fort Barrière',
          desc: 'Named by fur traders in 1828; believed to be near indigenous fish traps across the river.',
          lat: 51.1797,
          lng: -120.1236,
          img: require('../assets/fort-barriere.png'),
        },
        {
          id: 'north-thompson-museum-hist',
          name: 'North Thompson Museum',
          desc: 'Local heritage museum showing forestry, rail, pioneer life, and early education artifacts.',
          lat: 51.1776,
          lng: -120.1254,
          img: require('../assets/north-thompson-museum-hist.png'),
        },
        {
          id: 'replica-schoolhouse',
          name: 'Replica 1800s Schoolhouse',
          desc: 'Restored one-room school showing rural life in the late 19th century.',
          lat: 51.1776,
          lng: -120.1254,
          img: require('../assets/replica-schoolhouse.png'),
        },
        {
          id: 'trappers-cabin-steam-engine',
          name: 'Trapper’s Cabin & Steam Engine',
          desc: 'Preserved trapping-era cabin and vintage steam machinery display.',
          lat: 51.1776,
          lng: -120.1254,
          img: require('../assets/trappers-cabin.png'),
        },
        {
          id: 'simpcw-river-fishing-site',
          name: 'Simpcw River Fishing Site',
          desc: 'Traditional First Nations fish-weir location near Barrière River mouth.',
          lat: 51.18,
          lng: -120.12,
          img: require('../assets/simpcw-fishing-site.png'),
        },
      ],
    },
    {
      id: 'museums',
      title: 'Museums and galleries',
      cover: require('../assets/museums-cover.png'),
      items: [
        {
          id: 'north-thompson-museum',
          name: 'North Thompson Museum',
          desc: 'Main cultural hub with exhibits on regional settlement, trains, and indigenous history.',
          lat: 51.1776,
          lng: -120.1254,
          img: require('../assets/north-thompson-museum.png'),
        },
        {
          id: 'visitor-info-centre',
          name: 'Visitor Info Centre (Barrière)',
          desc: 'Small gallery-style center with local crafts, brochures, and cultural material.',
          lat: 51.18,
          lng: -120.123,
          img: require('../assets/visitor-info-centre.png'),
        },
        {
          id: 'gift-n-gab-trading-post',
          name: "Gift 'N Gab Trading Post",
          desc: 'A local art shop with rotating handmade goods, crafts and gallery displays.',
          lat: 51.1785,
          lng: -120.125,
          img: require('../assets/gift-n-gab.png'),
        },
        {
          id: 'barriere-library',
          name: 'Barrière Library',
          desc: 'Community library with public exhibits and occasional art installations.',
          lat: 51.1790,
          lng: -120.1245,
          img: require('../assets/barriere-library.png'),
        },
        {
          id: 'fadear-park-bandshell',
          name: 'Fadear Park Bandshell',
          desc: 'Open-air performance venue hosting cultural events and summer shows.',
          lat: 51.1795,
          lng: -120.1225,
          img: require('../assets/fadear-bandshell.png'),
        },
      ],
    },
    {
      id: 'parks',
      title: 'Parks and nature',
      cover: require('../assets/parks-cover.png'),
      items: [
        {
          id: 'fadear-park',
          name: 'Fadear Park',
          desc: 'Town’s main park with splash zone, skatepark, garden, and event area.',
          lat: 51.1795,
          lng: -120.1225,
          img: require('../assets/fadear-park.png'),
        },
        {
          id: 'community-park',
          name: 'Community Park',
          desc: 'Spacious park with dog area, tennis courts, and scenic river trails.',
          lat: 51.1788,
          lng: -120.1270,
          img: require('../assets/community-park.png'),
        },
        {
          id: 'oriole-park',
          name: 'Oriole Park',
          desc: 'Tranquil riverside park for casual strolls and relaxing views.',
          lat: 51.1810,
          lng: -120.1200,
          img: require('../assets/oriole-park.png'),
        },
        {
          id: 'bike-park-bmx',
          name: 'Bike Park (BMX)',
          desc: 'Volunteer-built dirt BMX track for all ages near downtown.',
          lat: 51.1790,
          lng: -120.1240,
          img: require('../assets/bike-park.png'),
        },
        {
          id: 'tsutswecw-provincial-park',
          name: 'Tsútswecw Provincial Park',
          desc: 'Salmon-run park ~10 km away, great for hiking and fish viewing.',
          lat: 51.2000,
          lng: -120.0500,
          img: require('../assets/tsutswecw-park.png'),
        },
      ],
    },
  ];
  